In [8]:
import numpy as np
import pandas as pd

In [69]:
# G = np.matrix([
#     [1, 0, 1, 0, 1, 1],
#     [1, 1, 1, 1, 0, 1],
#     [0, 1, 1, 0, 0, 1]
# ], dtype="u1")

G = np.matrix([
    [1, 1, 0, 0, 1, 0, 0],
    [1, 0, 1, 0, 0, 1, 0],
    [1, 0, 0, 1, 0, 0, 1],
    [1, 1, 1, 0, 0, 0, 1]
], dtype="u1")

k, n = G.shape
print(G)
k, n

[[1 1 0 0 1 0 0]
 [1 0 1 0 0 1 0]
 [1 0 0 1 0 0 1]
 [1 1 1 0 0 0 1]]


(4, 7)

In [71]:
k = G.shape[0]

A = np.matrix(np.identity(k), dtype="u1")
G_src = G.copy()[:,:k]
# print(G_src)
for i in range(k):
    col_i = np.array(G_src)[:,i]
    if col_i[i] == 1:
        A_i = np.identity(k)
        A_i[:,i] = col_i
        A_i = np.matrix(A_i, dtype="u1")
        A = A_i * A % 2
        # print(f"A_i=\n{A_i}")
        # print(f"A=\n{A}")
        G_src = A_i * G_src % 2
        # print(f"掃き出し{i + 1}回目")
        # print(G_src)

Tissue_G = A * G % 2
Tissue_G

matrix([[1, 0, 0, 0, 1, 1, 1],
        [0, 1, 0, 0, 0, 1, 1],
        [0, 0, 1, 0, 1, 0, 1],
        [0, 0, 0, 1, 1, 1, 0]], dtype=uint8)

In [72]:
all_src_ex0 = np.matrix([[int(j) for j in format(i, f"0{k}b")] for i in range(1, 2 ** k)], dtype="u1")
all_code_ex0 = all_src_ex0 * Tissue_G % 2
all_code_ex0_str = ["".join(str(i) for i in l) for l in all_code_ex0.tolist()]
all_code_ex0_str

['0001110',
 '0010101',
 '0011011',
 '0100011',
 '0101101',
 '0110110',
 '0111000',
 '1000111',
 '1001001',
 '1010010',
 '1011100',
 '1100100',
 '1101010',
 '1110001',
 '1111111']

In [82]:
# 1ビットエラー全パターン
all_error_str = [format(2 ** i, f"0{n}b") for i in range(n)]
# 適当に追加
all_error_str += ["1001000"]
all_error = np.matrix([[int(j) for j in moji] for moji in all_errors_str])
all_error_str

['0000001',
 '0000010',
 '0000100',
 '0001000',
 '0010000',
 '0100000',
 '1000000',
 '1001000']

In [85]:
std_arr_values = [["".join(str(k) for k in (e + w) % 2) for w in np.array(all_code_ex0)] for e in np.array(all_error)]
# std_arr_values

In [88]:
std_arr_df = pd.DataFrame(std_arr_values, columns=all_code_ex0_str, index=all_error_str)
std_arr_df

0001110  0010101  0011011  0100011  0101101  0110110  0111000  \
0000001  0001111  0010100  0011010  0100010  0101100  0110111  0111001   
0000010  0001100  0010111  0011001  0100001  0101111  0110100  0111010   
0000100  0001010  0010001  0011111  0100111  0101001  0110010  0111100   
0001000  0000110  0011101  0010011  0101011  0100101  0111110  0110000   
0010000  0011110  0000101  0001011  0110011  0111101  0100110  0101000   
0100000  0101110  0110101  0111011  0000011  0001101  0010110  0011000   
1000000  1001110  1010101  1011011  1100011  1101101  1110110  1111000   
1001000  1000110  1011101  1010011  1101011  1100101  1111110  1110000   

         1000111  1001001  1010010  1011100  1100100  1101010  1110001  \
0000001  1000110  1001000  1010011  1011101  1100101  1101011  1110000   
0000010  1000101  1001011  1010000  1011110  1100110  1101000  1110011   
0000100  1000011  1001101  1010110  1011000  1100000  1101110  1110101   
0001000  1001111  1000001  1011010  1010100  1101100  1100010  1111001   
0010000  1010111  1011001  1000010  1001100  1110100  1111010  1100001   
0100000  1100111  1101001  1110010  1111100  1000100  1001010  1010001   
1000000  0000111  0001001  0010010  0011100  0100100  0101010  0110001   
1001000  0001111  0000001  0011010  0010100  0101100  0100010  0111001   

         1111111  
0000001  1111110  
0000010  1111101  
0000100  1111011  
0001000  1110111  
0010000  1101111  
0100000  1011111  
1000000  0111111  
1001000  0110111