# (7, 4)ハミング符号のビット誤り率を知りたい

In [1]:
import numpy as np

In [17]:
G = np.matrix([
    [1, 0, 0, 0, 1, 1, 1],
    [0, 1, 0, 0, 0, 1, 1],
    [0, 0, 1, 0, 1, 0, 1],
    [0, 0, 0, 1, 1, 1, 0]
], dtype="u1")

k, n = G.shape

P = G[:, k:]
H = np.concatenate([P.T, np.identity(n - k, dtype="u1")], axis=1)

matrix([[1, 1, 1],
        [0, 1, 1],
        [1, 0, 1],
        [1, 1, 0],
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]], dtype=uint8)

In [50]:
N = 1
u = np.random.randint(0, 2, (N, k), dtype="u1")
u = np.matrix(u)
u

matrix([[0, 0, 0, 1]], dtype=uint8)

In [51]:
w = u * G & 1
w

matrix([[0, 0, 0, 1, 1, 1, 0]], dtype=uint8)