# (7, 4)ハミング符号のビット誤り率を知りたい

In [1]:
import numpy as np
import pandas as pd
from sympy import Symbol, Rational
from scipy.special import comb

In [2]:
def vec_to_str(vec: np.matrix):
    return "".join([str(i) for i in vec.tolist()[0]])

In [3]:
G = np.matrix([
    [1, 0, 0, 0, 1, 1, 1],
    [0, 1, 0, 0, 0, 1, 1],
    [0, 0, 1, 0, 1, 0, 1],
    [0, 0, 0, 1, 1, 1, 0]
], dtype="u1")

k, n = G.shape

P = G[:, k:]
H = np.concatenate([P.T, np.identity(n - k, dtype="u1")], axis=1)

In [4]:
N = 1
u = np.random.randint(0, 2, (N, k), dtype="u1")
u = np.matrix(u)
u

matrix([[0, 0, 0, 1]], dtype=uint8)

In [5]:
w = u * G & 1
w

matrix([[0, 0, 0, 1, 1, 1, 0]], dtype=uint8)

In [6]:
# 全誤りパターン (ただの7桁の全数値)
all_errors_str = [format(i, f"0{n}b") for i in range(1 << n)]
all_errors_matrix = np.matrix([[int(j) for j in i] for i in all_errors_str], dtype="u1")
all_errors_matrix

matrix([[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 1, 1],
        [0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 1, 0, 1],
        [0, 0, 0, 0, 1, 1, 0],
        [0, 0, 0, 0, 1, 1, 1],
        [0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 1],
        [0, 0, 0, 1, 0, 1, 0],
        [0, 0, 0, 1, 0, 1, 1],
        [0, 0, 0, 1, 1, 0, 0],
        [0, 0, 0, 1, 1, 0, 1],
        [0, 0, 0, 1, 1, 1, 0],
        [0, 0, 0, 1, 1, 1, 1],
        [0, 0, 1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 1],
        [0, 0, 1, 0, 0, 1, 0],
        [0, 0, 1, 0, 0, 1, 1],
        [0, 0, 1, 0, 1, 0, 0],
        [0, 0, 1, 0, 1, 0, 1],
        [0, 0, 1, 0, 1, 1, 0],
        [0, 0, 1, 0, 1, 1, 1],
        [0, 0, 1, 1, 0, 0, 0],
        [0, 0, 1, 1, 0, 0, 1],
        [0, 0, 1, 1, 0, 1, 0],
        [0, 0, 1, 1, 0, 1, 1],
        [0, 0, 1, 1, 1, 0, 0],
        [0, 0, 1, 1, 1, 0, 1],
        [0, 0, 1, 1, 1, 1, 0],
        [0, 0, 1, 1, 1, 1, 1],
        

In [7]:
error_bits_count_dict = {}
for i in range(n + 1):
    error_bits_count_dict[i] = np.matrix([j.tolist()[0] for j in all_errors_matrix if j.sum() == i], dtype="u1")
error_bits_count_dict

{0: matrix([[0, 0, 0, 0, 0, 0, 0]], dtype=uint8),
 1: matrix([[0, 0, 0, 0, 0, 0, 1],
         [0, 0, 0, 0, 0, 1, 0],
         [0, 0, 0, 0, 1, 0, 0],
         [0, 0, 0, 1, 0, 0, 0],
         [0, 0, 1, 0, 0, 0, 0],
         [0, 1, 0, 0, 0, 0, 0],
         [1, 0, 0, 0, 0, 0, 0]], dtype=uint8),
 2: matrix([[0, 0, 0, 0, 0, 1, 1],
         [0, 0, 0, 0, 1, 0, 1],
         [0, 0, 0, 0, 1, 1, 0],
         [0, 0, 0, 1, 0, 0, 1],
         [0, 0, 0, 1, 0, 1, 0],
         [0, 0, 0, 1, 1, 0, 0],
         [0, 0, 1, 0, 0, 0, 1],
         [0, 0, 1, 0, 0, 1, 0],
         [0, 0, 1, 0, 1, 0, 0],
         [0, 0, 1, 1, 0, 0, 0],
         [0, 1, 0, 0, 0, 0, 1],
         [0, 1, 0, 0, 0, 1, 0],
         [0, 1, 0, 0, 1, 0, 0],
         [0, 1, 0, 1, 0, 0, 0],
         [0, 1, 1, 0, 0, 0, 0],
         [1, 0, 0, 0, 0, 0, 1],
         [1, 0, 0, 0, 0, 1, 0],
         [1, 0, 0, 0, 1, 0, 0],
         [1, 0, 0, 1, 0, 0, 0],
         [1, 0, 1, 0, 0, 0, 0],
         [1, 1, 0, 0, 0, 0, 0]], dtype=uint8),
 3: matrix([[0, 0,

In [8]:
e = np.matrix(np.random.random((N, n)) < 1/7, dtype="u1")
e

matrix([[0, 0, 0, 0, 0, 0, 0]], dtype=uint8)

In [9]:
r = w ^ e
r

matrix([[0, 0, 0, 1, 1, 1, 0]], dtype=uint8)

In [10]:
s = r * H.T & 1
s

matrix([[0, 0, 0]], dtype=uint8)

In [11]:
est_e = np.matrix([np.array_equal(row, s) for row in H.T], dtype="u1")
est_e

matrix([[0, 0, 0, 0, 0, 0, 0]], dtype=uint8)

In [12]:
est_w = r ^ est_e
est_w

matrix([[0, 0, 0, 1, 1, 1, 0]], dtype=uint8)

In [13]:
est_u = est_w[:, :k]
est_u

matrix([[0, 0, 0, 1]], dtype=uint8)

In [14]:
# 全情報源パターン
all_src_str = [format(i, f"0{k}b") for i in range(1 << k)]
all_src_matrix = np.matrix([[int(j) for j in i] for i in all_src_str], dtype="u1")
all_code_matrix = all_src_matrix * G & 1
all_code_matrix

matrix([[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 1, 1, 0],
        [0, 0, 1, 0, 1, 0, 1],
        [0, 0, 1, 1, 0, 1, 1],
        [0, 1, 0, 0, 0, 1, 1],
        [0, 1, 0, 1, 1, 0, 1],
        [0, 1, 1, 0, 1, 1, 0],
        [0, 1, 1, 1, 0, 0, 0],
        [1, 0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 0, 0, 1],
        [1, 0, 1, 0, 0, 1, 0],
        [1, 0, 1, 1, 1, 0, 0],
        [1, 1, 0, 0, 1, 0, 0],
        [1, 1, 0, 1, 0, 1, 0],
        [1, 1, 1, 0, 0, 0, 1],
        [1, 1, 1, 1, 1, 1, 1]], dtype=uint8)

In [15]:
bit_error_sum_df = pd.DataFrame(index=all_src_str, columns=[f"err_{i}" for i in range(n + 1)])
n_error_patterns_count_list = [error_bits_count_dict[i].shape[0] for i in range(n + 1)]
# 全ての符号について調べる
for w in all_code_matrix:
    u = w[:, :k]
    u_str = vec_to_str(u)
    # 誤りビット数ごとに調べる
    for i in range(n + 1):
        n_error_patterns = error_bits_count_dict[i]
        bit_error_sum = 0
        for e in n_error_patterns:
            r = w ^ e
            s = r * H.T & 1
            est_e = np.matrix([np.array_equal(row, s) for row in H.T], dtype="u1")
            est_w = r ^ est_e
            est_u = est_w[:, :k]
            dif_u = u ^ est_u
            
#             print(u_str, vec_to_str(e), vec_to_str(est_u))
            bit_error_sum += dif_u.sum()
        bit_error_sum_df[f"err_{i}"][u_str] = int(bit_error_sum)

In [16]:
bit_error_sum_df

err_0 err_1 err_2 err_3 err_4 err_5 err_6 err_7
0000     0     0    36    76    64    48    28     4
0001     0     0    36    76    64    48    28     4
0010     0     0    36    76    64    48    28     4
0011     0     0    36    76    64    48    28     4
0100     0     0    36    76    64    48    28     4
0101     0     0    36    76    64    48    28     4
0110     0     0    36    76    64    48    28     4
0111     0     0    36    76    64    48    28     4
1000     0     0    36    76    64    48    28     4
1001     0     0    36    76    64    48    28     4
1010     0     0    36    76    64    48    28     4
1011     0     0    36    76    64    48    28     4
1100     0     0    36    76    64    48    28     4
1101     0     0    36    76    64    48    28     4
1110     0     0    36    76    64    48    28     4
1111     0     0    36    76    64    48    28     4

In [26]:
pd.options.display.float_format = "{:.4f}".format

print(n_error_patterns_count_list)
bit_error_sum_list = bit_error_sum_df.iloc[0].tolist()
bit_error_mean_df = bit_error_sum_df / n_error_patterns_count_list
bit_error_mean_df

[1, 7, 21, 35, 35, 21, 7, 1]


err_0  err_1  err_2  err_3  err_4  err_5  err_6  err_7
0000 0.0000 0.0000 1.7143 2.1714 1.8286 2.2857 4.0000 4.0000
0001 0.0000 0.0000 1.7143 2.1714 1.8286 2.2857 4.0000 4.0000
0010 0.0000 0.0000 1.7143 2.1714 1.8286 2.2857 4.0000 4.0000
0011 0.0000 0.0000 1.7143 2.1714 1.8286 2.2857 4.0000 4.0000
0100 0.0000 0.0000 1.7143 2.1714 1.8286 2.2857 4.0000 4.0000
0101 0.0000 0.0000 1.7143 2.1714 1.8286 2.2857 4.0000 4.0000
0110 0.0000 0.0000 1.7143 2.1714 1.8286 2.2857 4.0000 4.0000
0111 0.0000 0.0000 1.7143 2.1714 1.8286 2.2857 4.0000 4.0000
1000 0.0000 0.0000 1.7143 2.1714 1.8286 2.2857 4.0000 4.0000
1001 0.0000 0.0000 1.7143 2.1714 1.8286 2.2857 4.0000 4.0000
1010 0.0000 0.0000 1.7143 2.1714 1.8286 2.2857 4.0000 4.0000
1011 0.0000 0.0000 1.7143 2.1714 1.8286 2.2857 4.0000 4.0000
1100 0.0000 0.0000 1.7143 2.1714 1.8286 2.2857 4.0000 4.0000
1101 0.0000 0.0000 1.7143 2.1714 1.8286 2.2857 4.0000 4.0000
1110 0.0000 0.0000 1.7143 2.1714 1.8286 2.2857 4.0000 4.0000
1111 0.0000 0.0000 1.7143 2.1714 1.8286 2.2857 4.0000 4.0000

### ビット誤り率 (Bit Error Rate) の理論値算出

In [18]:
p = Symbol("p")
q = Symbol("q")

In [19]:
repetition_ber = sum(comb(3, i, True) *  p ** i * q ** (3 - i) for i in range(2, 4))
repetition_ber

p**3 + 3*p**2*q

In [20]:
repetition_ber = repetition_ber.subs(q, 1 - p)
repetition_ber = repetition_ber.simplify()
repetition_ber

p**2*(3 - 2*p)

In [21]:
hamming_ber = sum(p ** i * q ** (n - i) * bit_error_sum_list[i] for i in range(n + 1))

# 4ビットのうちの誤りビット数の期待値なので, 4で割る
hamming_ber /= 4
hamming_ber

p**7 + 7*p**6*q + 12*p**5*q**2 + 16*p**4*q**3 + 19*p**3*q**4 + 9*p**2*q**5

In [22]:
hamming_ber = hamming_ber.subs(q, 1 - p)
hamming_ber = hamming_ber.simplify()
hamming_ber

p**2*(-12*p**3 + 30*p**2 - 26*p + 9)

In [38]:
e_prob_arr = np.logspace(-7, -0.5, 14)

repetition_ber_arr = np.array(list(map(lambda x: repetition_ber.subs(p, x), e_prob_arr)), dtype="f8")
hamming_ber_arr = np.array(list(map(lambda x: hamming_ber.subs(p, x), e_prob_arr)), dtype="f8")
e_prob_arr_str = [f"{i:.5e}" for i in e_prob_arr]

pd.options.display.float_format = "{:.5e}".format

ber_df =  pd.DataFrame(np.stack([repetition_ber_arr, hamming_ber_arr]).T, index=e_prob_arr_str, columns=["repetition", "hamming"])
ber_df

repetition     hamming
1.00000e-07 3.00000e-14 9.00000e-14
3.16228e-07 3.00000e-13 8.99999e-13
1.00000e-06 3.00000e-12 8.99997e-12
3.16228e-06 2.99999e-11 8.99992e-11
1.00000e-05 2.99998e-10 8.99974e-10
3.16228e-05 2.99994e-09 8.99918e-09
1.00000e-04 2.99980e-08 8.99740e-08
3.16228e-04 2.99937e-07 8.99178e-07
1.00000e-03 2.99800e-06 8.97403e-06
3.16228e-03 2.99368e-05 8.91808e-05
1.00000e-02 2.98000e-04 8.74299e-04
3.16228e-02 2.93675e-03 8.20743e-03
1.00000e-01 2.80000e-02 6.68800e-02
3.16228e-01 2.36754e-01 3.39860e-01

### 符号化なしとのビット誤り率の比率

In [44]:
ber_ratio_df = (ber_df.T / e_prob_arr).T
ber_ratio_df

repetition     hamming
1.00000e-07 3.00000e-07 9.00000e-07
3.16228e-07 9.48683e-07 2.84605e-06
1.00000e-06 3.00000e-06 8.99997e-06
3.16228e-06 9.48681e-06 2.84602e-05
1.00000e-05 2.99998e-05 8.99974e-05
3.16228e-05 9.48663e-05 2.84579e-04
1.00000e-04 2.99980e-04 8.99740e-04
3.16228e-04 9.48483e-04 2.84345e-03
1.00000e-03 2.99800e-03 8.97403e-03
3.16228e-03 9.46683e-03 2.82014e-02
1.00000e-02 2.98000e-02 8.74299e-02
3.16228e-02 9.28683e-02 2.59542e-01
1.00000e-01 2.80000e-01 6.68800e-01
3.16228e-01 7.48683e-01 1.07473e+00

In [47]:
# 符号なしのビット誤り数の期待値を固定したとき, 他のビット誤り数の期待値を計算
# シミューレーションの予測用
ber_ratio_df * 1000000

repetition     hamming
1.00000e-07 3.00000e-02 9.00000e-02
3.16228e-07 9.48683e-02 2.84605e-01
1.00000e-06 3.00000e-01 8.99997e-01
3.16228e-06 9.48681e-01 2.84602e+00
1.00000e-05 2.99998e+00 8.99974e+00
3.16228e-05 9.48663e+00 2.84579e+01
1.00000e-04 2.99980e+01 8.99740e+01
3.16228e-04 9.48483e+01 2.84345e+02
1.00000e-03 2.99800e+02 8.97403e+02
3.16228e-03 9.46683e+02 2.82014e+03
1.00000e-02 2.98000e+03 8.74299e+03
3.16228e-02 9.28683e+03 2.59542e+04
1.00000e-01 2.80000e+04 6.68800e+04
3.16228e-01 7.48683e+04 1.07473e+05