# (7, 4)ハミング符号のビット誤り率を知りたい

In [1]:
import numpy as np

In [2]:
G = np.matrix([
    [1, 0, 0, 0, 1, 1, 1],
    [0, 1, 0, 0, 0, 1, 1],
    [0, 0, 1, 0, 1, 0, 1],
    [0, 0, 0, 1, 1, 1, 0]
], dtype="u1")

k, n = G.shape

P = G[:, k:]
H = np.concatenate([P.T, np.identity(n - k, dtype="u1")], axis=1)

In [3]:
N = 1
u = np.random.randint(0, 2, (N, k), dtype="u1")
u = np.matrix(u)
u

matrix([[0, 0, 1, 0]], dtype=uint8)

In [4]:
w = u * G & 1
w

matrix([[0, 0, 1, 0, 1, 0, 1]], dtype=uint8)

In [5]:
# 全誤りパターン (ただの7桁の全数値)
all_errors_str = [format(i, f"0{n}b") for i in range(1 << n)]
all_errors_matrix = np.matrix([[int(j) for j in i] for i in all_errors_str], dtype="u1")
all_errors_matrix

matrix([[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 1, 1],
        [0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 1, 0, 1],
        [0, 0, 0, 0, 1, 1, 0],
        [0, 0, 0, 0, 1, 1, 1],
        [0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 1],
        [0, 0, 0, 1, 0, 1, 0],
        [0, 0, 0, 1, 0, 1, 1],
        [0, 0, 0, 1, 1, 0, 0],
        [0, 0, 0, 1, 1, 0, 1],
        [0, 0, 0, 1, 1, 1, 0],
        [0, 0, 0, 1, 1, 1, 1],
        [0, 0, 1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 1],
        [0, 0, 1, 0, 0, 1, 0],
        [0, 0, 1, 0, 0, 1, 1],
        [0, 0, 1, 0, 1, 0, 0],
        [0, 0, 1, 0, 1, 0, 1],
        [0, 0, 1, 0, 1, 1, 0],
        [0, 0, 1, 0, 1, 1, 1],
        [0, 0, 1, 1, 0, 0, 0],
        [0, 0, 1, 1, 0, 0, 1],
        [0, 0, 1, 1, 0, 1, 0],
        [0, 0, 1, 1, 0, 1, 1],
        [0, 0, 1, 1, 1, 0, 0],
        [0, 0, 1, 1, 1, 0, 1],
        [0, 0, 1, 1, 1, 1, 0],
        [0, 0, 1, 1, 1, 1, 1],
        

In [6]:
error_bits_count_dict = {}
for i in range(n + 1):
    error_bits_count_dict[i] = np.matrix([j.tolist()[0] for j in all_errors_matrix if j.sum() == i], dtype="u1")
error_bits_count_dict

{0: matrix([[0, 0, 0, 0, 0, 0, 0]], dtype=uint8),
 1: matrix([[0, 0, 0, 0, 0, 0, 1],
         [0, 0, 0, 0, 0, 1, 0],
         [0, 0, 0, 0, 1, 0, 0],
         [0, 0, 0, 1, 0, 0, 0],
         [0, 0, 1, 0, 0, 0, 0],
         [0, 1, 0, 0, 0, 0, 0],
         [1, 0, 0, 0, 0, 0, 0]], dtype=uint8),
 2: matrix([[0, 0, 0, 0, 0, 1, 1],
         [0, 0, 0, 0, 1, 0, 1],
         [0, 0, 0, 0, 1, 1, 0],
         [0, 0, 0, 1, 0, 0, 1],
         [0, 0, 0, 1, 0, 1, 0],
         [0, 0, 0, 1, 1, 0, 0],
         [0, 0, 1, 0, 0, 0, 1],
         [0, 0, 1, 0, 0, 1, 0],
         [0, 0, 1, 0, 1, 0, 0],
         [0, 0, 1, 1, 0, 0, 0],
         [0, 1, 0, 0, 0, 0, 1],
         [0, 1, 0, 0, 0, 1, 0],
         [0, 1, 0, 0, 1, 0, 0],
         [0, 1, 0, 1, 0, 0, 0],
         [0, 1, 1, 0, 0, 0, 0],
         [1, 0, 0, 0, 0, 0, 1],
         [1, 0, 0, 0, 0, 1, 0],
         [1, 0, 0, 0, 1, 0, 0],
         [1, 0, 0, 1, 0, 0, 0],
         [1, 0, 1, 0, 0, 0, 0],
         [1, 1, 0, 0, 0, 0, 0]], dtype=uint8),
 3: matrix([[0, 0,

In [7]:
e = np.matrix(np.random.random((N, n)) < 1/7, dtype="u1")
e

matrix([[0, 0, 1, 0, 0, 0, 0]], dtype=uint8)

In [8]:
r = w ^ e
r

matrix([[0, 0, 0, 0, 1, 0, 1]], dtype=uint8)

In [9]:
s = r * H.T & 1
s

matrix([[1, 0, 1]], dtype=uint8)

In [10]:
est_e = np.matrix([np.array_equal(row, s) for row in H.T], dtype="u1")
est_e

matrix([[0, 0, 1, 0, 0, 0, 0]], dtype=uint8)

In [11]:
est_w = r ^ est_e
est_w

matrix([[0, 0, 1, 0, 1, 0, 1]], dtype=uint8)

In [12]:
est_u = est_w[:, :k]
est_u

matrix([[0, 0, 1, 0]], dtype=uint8)

In [13]:

for i, n_error_patterns in error_bits_count_dict.items():
    n_error_patterns_count = len(n_error_patterns)
#     print(n_error_patterns_count)
    bit_error_sum = 0
    for e in n_error_patterns:
        r = w ^ e
        s = r * H.T & 1
        est_e = np.matrix([np.array_equal(row, s) for row in H.T], dtype="u1")
        est_w = r ^ est_e
        est_u = est_w[:, :k]
        dif_u = u ^ est_u
#         print(dif_u)
        bit_error_sum += dif_u.sum()
    bit_error_mean = bit_error_sum / n_error_patterns_count
    print(n_error_patterns_count, bit_error_sum, bit_error_mean)

1 0.0 0.0
7 0.0 0.0
21 36.0 1.7142857142857142
35 76.0 2.1714285714285713
35 64.0 1.8285714285714285
21 48.0 2.2857142857142856
7 28.0 4.0
1 4.0 4.0


In [14]:
# 全情報源パターン
all_src_str = [format(i, f"0{k}b") for i in range(1 << k)]
all_src_matrix = np.matrix([[int(j) for j in i] for i in all_src_str], dtype="u1")
all_src_matrix

matrix([[0, 0, 0, 0],
        [0, 0, 0, 1],
        [0, 0, 1, 0],
        [0, 0, 1, 1],
        [0, 1, 0, 0],
        [0, 1, 0, 1],
        [0, 1, 1, 0],
        [0, 1, 1, 1],
        [1, 0, 0, 0],
        [1, 0, 0, 1],
        [1, 0, 1, 0],
        [1, 0, 1, 1],
        [1, 1, 0, 0],
        [1, 1, 0, 1],
        [1, 1, 1, 0],
        [1, 1, 1, 1]], dtype=uint8)