# (7, 4)ハミング符号のビット誤り率を知りたい

In [46]:
import numpy as np
import pandas as pd
from sympy import Symbol, Rational
from scipy.special import comb

In [2]:
def vec_to_str(vec: np.matrix):
    return "".join([str(i) for i in vec.tolist()[0]])

In [3]:
G = np.matrix([
    [1, 0, 0, 0, 1, 1, 1],
    [0, 1, 0, 0, 0, 1, 1],
    [0, 0, 1, 0, 1, 0, 1],
    [0, 0, 0, 1, 1, 1, 0]
], dtype="u1")

k, n = G.shape

P = G[:, k:]
H = np.concatenate([P.T, np.identity(n - k, dtype="u1")], axis=1)

In [4]:
N = 1
u = np.random.randint(0, 2, (N, k), dtype="u1")
u = np.matrix(u)
u

matrix([[0, 1, 1, 1]], dtype=uint8)

In [5]:
w = u * G & 1
w

matrix([[0, 1, 1, 1, 0, 0, 0]], dtype=uint8)

In [6]:
# 全誤りパターン (ただの7桁の全数値)
all_errors_str = [format(i, f"0{n}b") for i in range(1 << n)]
all_errors_matrix = np.matrix([[int(j) for j in i] for i in all_errors_str], dtype="u1")
all_errors_matrix

matrix([[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 1, 1],
        [0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 1, 0, 1],
        [0, 0, 0, 0, 1, 1, 0],
        [0, 0, 0, 0, 1, 1, 1],
        [0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 1],
        [0, 0, 0, 1, 0, 1, 0],
        [0, 0, 0, 1, 0, 1, 1],
        [0, 0, 0, 1, 1, 0, 0],
        [0, 0, 0, 1, 1, 0, 1],
        [0, 0, 0, 1, 1, 1, 0],
        [0, 0, 0, 1, 1, 1, 1],
        [0, 0, 1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 1],
        [0, 0, 1, 0, 0, 1, 0],
        [0, 0, 1, 0, 0, 1, 1],
        [0, 0, 1, 0, 1, 0, 0],
        [0, 0, 1, 0, 1, 0, 1],
        [0, 0, 1, 0, 1, 1, 0],
        [0, 0, 1, 0, 1, 1, 1],
        [0, 0, 1, 1, 0, 0, 0],
        [0, 0, 1, 1, 0, 0, 1],
        [0, 0, 1, 1, 0, 1, 0],
        [0, 0, 1, 1, 0, 1, 1],
        [0, 0, 1, 1, 1, 0, 0],
        [0, 0, 1, 1, 1, 0, 1],
        [0, 0, 1, 1, 1, 1, 0],
        [0, 0, 1, 1, 1, 1, 1],
        

In [7]:
error_bits_count_dict = {}
for i in range(n + 1):
    error_bits_count_dict[i] = np.matrix([j.tolist()[0] for j in all_errors_matrix if j.sum() == i], dtype="u1")
error_bits_count_dict

{0: matrix([[0, 0, 0, 0, 0, 0, 0]], dtype=uint8),
 1: matrix([[0, 0, 0, 0, 0, 0, 1],
         [0, 0, 0, 0, 0, 1, 0],
         [0, 0, 0, 0, 1, 0, 0],
         [0, 0, 0, 1, 0, 0, 0],
         [0, 0, 1, 0, 0, 0, 0],
         [0, 1, 0, 0, 0, 0, 0],
         [1, 0, 0, 0, 0, 0, 0]], dtype=uint8),
 2: matrix([[0, 0, 0, 0, 0, 1, 1],
         [0, 0, 0, 0, 1, 0, 1],
         [0, 0, 0, 0, 1, 1, 0],
         [0, 0, 0, 1, 0, 0, 1],
         [0, 0, 0, 1, 0, 1, 0],
         [0, 0, 0, 1, 1, 0, 0],
         [0, 0, 1, 0, 0, 0, 1],
         [0, 0, 1, 0, 0, 1, 0],
         [0, 0, 1, 0, 1, 0, 0],
         [0, 0, 1, 1, 0, 0, 0],
         [0, 1, 0, 0, 0, 0, 1],
         [0, 1, 0, 0, 0, 1, 0],
         [0, 1, 0, 0, 1, 0, 0],
         [0, 1, 0, 1, 0, 0, 0],
         [0, 1, 1, 0, 0, 0, 0],
         [1, 0, 0, 0, 0, 0, 1],
         [1, 0, 0, 0, 0, 1, 0],
         [1, 0, 0, 0, 1, 0, 0],
         [1, 0, 0, 1, 0, 0, 0],
         [1, 0, 1, 0, 0, 0, 0],
         [1, 1, 0, 0, 0, 0, 0]], dtype=uint8),
 3: matrix([[0, 0,

In [8]:
e = np.matrix(np.random.random((N, n)) < 1/7, dtype="u1")
e

matrix([[0, 0, 0, 0, 0, 0, 0]], dtype=uint8)

In [9]:
r = w ^ e
r

matrix([[0, 1, 1, 1, 0, 0, 0]], dtype=uint8)

In [10]:
s = r * H.T & 1
s

matrix([[0, 0, 0]], dtype=uint8)

In [11]:
est_e = np.matrix([np.array_equal(row, s) for row in H.T], dtype="u1")
est_e

matrix([[0, 0, 0, 0, 0, 0, 0]], dtype=uint8)

In [12]:
est_w = r ^ est_e
est_w

matrix([[0, 1, 1, 1, 0, 0, 0]], dtype=uint8)

In [13]:
est_u = est_w[:, :k]
est_u

matrix([[0, 1, 1, 1]], dtype=uint8)

In [14]:
# 全情報源パターン
all_src_str = [format(i, f"0{k}b") for i in range(1 << k)]
all_src_matrix = np.matrix([[int(j) for j in i] for i in all_src_str], dtype="u1")
all_code_matrix = all_src_matrix * G & 1
all_code_matrix

matrix([[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 1, 1, 0],
        [0, 0, 1, 0, 1, 0, 1],
        [0, 0, 1, 1, 0, 1, 1],
        [0, 1, 0, 0, 0, 1, 1],
        [0, 1, 0, 1, 1, 0, 1],
        [0, 1, 1, 0, 1, 1, 0],
        [0, 1, 1, 1, 0, 0, 0],
        [1, 0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 0, 0, 1],
        [1, 0, 1, 0, 0, 1, 0],
        [1, 0, 1, 1, 1, 0, 0],
        [1, 1, 0, 0, 1, 0, 0],
        [1, 1, 0, 1, 0, 1, 0],
        [1, 1, 1, 0, 0, 0, 1],
        [1, 1, 1, 1, 1, 1, 1]], dtype=uint8)

In [24]:
bit_error_sum_df = pd.DataFrame(index=all_src_str, columns=[f"err_{i}" for i in range(n + 1)])
n_error_patterns_count_list = [error_bits_count_dict[i].shape[0] for i in range(n + 1)]
# 全ての符号について調べる
for w in all_code_matrix:
    u = w[:, :k]
    u_str = vec_to_str(u)
    # 誤りビット数ごとに調べる
    for i in range(n + 1):
        n_error_patterns = error_bits_count_dict[i]
        bit_error_sum = 0
        for e in n_error_patterns:
            r = w ^ e
            s = r * H.T & 1
            est_e = np.matrix([np.array_equal(row, s) for row in H.T], dtype="u1")
            est_w = r ^ est_e
            est_u = est_w[:, :k]
            dif_u = u ^ est_u
            
#             print(u_str, vec_to_str(e), vec_to_str(est_u))
            bit_error_sum += dif_u.sum()
        bit_error_sum_df[f"err_{i}"][u_str] = int(bit_error_sum)

In [25]:
bit_error_sum_df

err_0 err_1 err_2 err_3 err_4 err_5 err_6 err_7
0000     0     0    36    76    64    48    28     4
0001     0     0    36    76    64    48    28     4
0010     0     0    36    76    64    48    28     4
0011     0     0    36    76    64    48    28     4
0100     0     0    36    76    64    48    28     4
0101     0     0    36    76    64    48    28     4
0110     0     0    36    76    64    48    28     4
0111     0     0    36    76    64    48    28     4
1000     0     0    36    76    64    48    28     4
1001     0     0    36    76    64    48    28     4
1010     0     0    36    76    64    48    28     4
1011     0     0    36    76    64    48    28     4
1100     0     0    36    76    64    48    28     4
1101     0     0    36    76    64    48    28     4
1110     0     0    36    76    64    48    28     4
1111     0     0    36    76    64    48    28     4

In [61]:
print(n_error_patterns_count_list)
bit_error_sum_list = bit_error_sum_df.iloc[0].tolist()
bit_error_mean_df = bit_error_sum_df / n_error_patterns_count_list
bit_error_mean_df

[1, 7, 21, 35, 35, 21, 7, 1]


err_0 err_1     err_2     err_3     err_4     err_5 err_6 err_7
0000   0.0   0.0  1.714286  2.171429  1.828571  2.285714   4.0   4.0
0001   0.0   0.0  1.714286  2.171429  1.828571  2.285714   4.0   4.0
0010   0.0   0.0  1.714286  2.171429  1.828571  2.285714   4.0   4.0
0011   0.0   0.0  1.714286  2.171429  1.828571  2.285714   4.0   4.0
0100   0.0   0.0  1.714286  2.171429  1.828571  2.285714   4.0   4.0
0101   0.0   0.0  1.714286  2.171429  1.828571  2.285714   4.0   4.0
0110   0.0   0.0  1.714286  2.171429  1.828571  2.285714   4.0   4.0
0111   0.0   0.0  1.714286  2.171429  1.828571  2.285714   4.0   4.0
1000   0.0   0.0  1.714286  2.171429  1.828571  2.285714   4.0   4.0
1001   0.0   0.0  1.714286  2.171429  1.828571  2.285714   4.0   4.0
1010   0.0   0.0  1.714286  2.171429  1.828571  2.285714   4.0   4.0
1011   0.0   0.0  1.714286  2.171429  1.828571  2.285714   4.0   4.0
1100   0.0   0.0  1.714286  2.171429  1.828571  2.285714   4.0   4.0
1101   0.0   0.0  1.714286  2.171429  1.828571  2.285714   4.0   4.0
1110   0.0   0.0  1.714286  2.171429  1.828571  2.285714   4.0   4.0
1111   0.0   0.0  1.714286  2.171429  1.828571  2.285714   4.0   4.0

In [91]:
p = Symbol("p")
q = Symbol("q")
binomial = 0
for i in range(n + 1):
    binomial += comb(n, i) * p ** i * q ** (n - i) * bit_error_sum_list[i] / n_error_patterns_count_list[i]
binomial

4.0*p**7 + 28.0*p**6*q + 48.0*p**5*q**2 + 64.0*p**4*q**3 + 76.0*p**3*q**4 + 36.0*p**2*q**5

In [92]:
binomial = binomial.subs(q, 1 - p)
binomial

4.0*p**7 + 28.0*p**6*(1 - p) + 48.0*p**5*(1 - p)**2 + 64.0*p**4*(1 - p)**3 + 76.0*p**3*(1 - p)**4 + 36.0*p**2*(1 - p)**5

In [114]:
ans = binomial.subs(p, np.power(10, -4.0-1/4))

In [115]:
ans * 1e10

1138.23502860170

In [116]:
np.power(10, -4.0-1/4)

5.623413251903491e-05