# (7, 4)ハミング符号のビット誤り率を知りたい

In [1]:
import numpy as np

In [17]:
G = np.matrix([
    [1, 0, 0, 0, 1, 1, 1],
    [0, 1, 0, 0, 0, 1, 1],
    [0, 0, 1, 0, 1, 0, 1],
    [0, 0, 0, 1, 1, 1, 0]
], dtype="u1")

k, n = G.shape

P = G[:, k:]
H = np.concatenate([P.T, np.identity(n - k, dtype="u1")], axis=1)

matrix([[1, 1, 1],
        [0, 1, 1],
        [1, 0, 1],
        [1, 1, 0],
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]], dtype=uint8)

In [50]:
N = 1
u = np.random.randint(0, 2, (N, k), dtype="u1")
u = np.matrix(u)
u

matrix([[0, 0, 0, 1]], dtype=uint8)

In [51]:
w = u * G & 1
w

matrix([[0, 0, 0, 1, 1, 1, 0]], dtype=uint8)

In [56]:
# 全誤りパターン (ただの7桁の全数値)
all_errors_str = [format(i, f"0{n}b") for i in range(1 << n)]
all_errors_matrix = [np.matrix([int(j) for j in i], dtype="u1") for i in all_errors_str]
all_errors_matrix

[matrix([[0, 0, 0, 0, 0, 0, 0]], dtype=uint8),
 matrix([[0, 0, 0, 0, 0, 0, 1]], dtype=uint8),
 matrix([[0, 0, 0, 0, 0, 1, 0]], dtype=uint8),
 matrix([[0, 0, 0, 0, 0, 1, 1]], dtype=uint8),
 matrix([[0, 0, 0, 0, 1, 0, 0]], dtype=uint8),
 matrix([[0, 0, 0, 0, 1, 0, 1]], dtype=uint8),
 matrix([[0, 0, 0, 0, 1, 1, 0]], dtype=uint8),
 matrix([[0, 0, 0, 0, 1, 1, 1]], dtype=uint8),
 matrix([[0, 0, 0, 1, 0, 0, 0]], dtype=uint8),
 matrix([[0, 0, 0, 1, 0, 0, 1]], dtype=uint8),
 matrix([[0, 0, 0, 1, 0, 1, 0]], dtype=uint8),
 matrix([[0, 0, 0, 1, 0, 1, 1]], dtype=uint8),
 matrix([[0, 0, 0, 1, 1, 0, 0]], dtype=uint8),
 matrix([[0, 0, 0, 1, 1, 0, 1]], dtype=uint8),
 matrix([[0, 0, 0, 1, 1, 1, 0]], dtype=uint8),
 matrix([[0, 0, 0, 1, 1, 1, 1]], dtype=uint8),
 matrix([[0, 0, 1, 0, 0, 0, 0]], dtype=uint8),
 matrix([[0, 0, 1, 0, 0, 0, 1]], dtype=uint8),
 matrix([[0, 0, 1, 0, 0, 1, 0]], dtype=uint8),
 matrix([[0, 0, 1, 0, 0, 1, 1]], dtype=uint8),
 matrix([[0, 0, 1, 0, 1, 0, 0]], dtype=uint8),
 matrix([[0, 

In [57]:
error_bits_count_dict = {}
for i in range(n):
    pass

3

In [59]:
[i for i in all_errors_matrix if i.sum() == 3]

[matrix([[0, 0, 0, 0, 1, 1, 1]], dtype=uint8),
 matrix([[0, 0, 0, 1, 0, 1, 1]], dtype=uint8),
 matrix([[0, 0, 0, 1, 1, 0, 1]], dtype=uint8),
 matrix([[0, 0, 0, 1, 1, 1, 0]], dtype=uint8),
 matrix([[0, 0, 1, 0, 0, 1, 1]], dtype=uint8),
 matrix([[0, 0, 1, 0, 1, 0, 1]], dtype=uint8),
 matrix([[0, 0, 1, 0, 1, 1, 0]], dtype=uint8),
 matrix([[0, 0, 1, 1, 0, 0, 1]], dtype=uint8),
 matrix([[0, 0, 1, 1, 0, 1, 0]], dtype=uint8),
 matrix([[0, 0, 1, 1, 1, 0, 0]], dtype=uint8),
 matrix([[0, 1, 0, 0, 0, 1, 1]], dtype=uint8),
 matrix([[0, 1, 0, 0, 1, 0, 1]], dtype=uint8),
 matrix([[0, 1, 0, 0, 1, 1, 0]], dtype=uint8),
 matrix([[0, 1, 0, 1, 0, 0, 1]], dtype=uint8),
 matrix([[0, 1, 0, 1, 0, 1, 0]], dtype=uint8),
 matrix([[0, 1, 0, 1, 1, 0, 0]], dtype=uint8),
 matrix([[0, 1, 1, 0, 0, 0, 1]], dtype=uint8),
 matrix([[0, 1, 1, 0, 0, 1, 0]], dtype=uint8),
 matrix([[0, 1, 1, 0, 1, 0, 0]], dtype=uint8),
 matrix([[0, 1, 1, 1, 0, 0, 0]], dtype=uint8),
 matrix([[1, 0, 0, 0, 0, 1, 1]], dtype=uint8),
 matrix([[1, 