# (7, 4)ハミング符号のビット誤り率を知りたい

In [1]:
import numpy as np

In [17]:
G = np.matrix([
    [1, 0, 0, 0, 1, 1, 1],
    [0, 1, 0, 0, 0, 1, 1],
    [0, 0, 1, 0, 1, 0, 1],
    [0, 0, 0, 1, 1, 1, 0]
], dtype="u1")

k, n = G.shape

P = G[:, k:]
H = np.concatenate([P.T, np.identity(n - k, dtype="u1")], axis=1)

matrix([[1, 1, 1],
        [0, 1, 1],
        [1, 0, 1],
        [1, 1, 0],
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]], dtype=uint8)

In [50]:
N = 1
u = np.random.randint(0, 2, (N, k), dtype="u1")
u = np.matrix(u)
u

matrix([[0, 0, 0, 1]], dtype=uint8)

In [51]:
w = u * G & 1
w

matrix([[0, 0, 0, 1, 1, 1, 0]], dtype=uint8)

In [54]:
# 全誤りパターン (ただの7桁の全数値)
all_errors_str = [format(i, f"0{n}b") for i in range(1 << n)]
all_errors_str

['0000000',
 '0000001',
 '0000010',
 '0000011',
 '0000100',
 '0000101',
 '0000110',
 '0000111',
 '0001000',
 '0001001',
 '0001010',
 '0001011',
 '0001100',
 '0001101',
 '0001110',
 '0001111',
 '0010000',
 '0010001',
 '0010010',
 '0010011',
 '0010100',
 '0010101',
 '0010110',
 '0010111',
 '0011000',
 '0011001',
 '0011010',
 '0011011',
 '0011100',
 '0011101',
 '0011110',
 '0011111',
 '0100000',
 '0100001',
 '0100010',
 '0100011',
 '0100100',
 '0100101',
 '0100110',
 '0100111',
 '0101000',
 '0101001',
 '0101010',
 '0101011',
 '0101100',
 '0101101',
 '0101110',
 '0101111',
 '0110000',
 '0110001',
 '0110010',
 '0110011',
 '0110100',
 '0110101',
 '0110110',
 '0110111',
 '0111000',
 '0111001',
 '0111010',
 '0111011',
 '0111100',
 '0111101',
 '0111110',
 '0111111',
 '1000000',
 '1000001',
 '1000010',
 '1000011',
 '1000100',
 '1000101',
 '1000110',
 '1000111',
 '1001000',
 '1001001',
 '1001010',
 '1001011',
 '1001100',
 '1001101',
 '1001110',
 '1001111',
 '1010000',
 '1010001',
 '1010010',
 '10